workflow/static/js/edit_job_form_autosave.js, workflow/static/js/job_file_handling.js, workflow/templates/jobs/edit_job_detail_section.html
```python
job_folder = os.path.join(settings.DROPBOX_WORKFLOW_FOLDER, f"Job-{job_number}")
file_path = os.path.join(job_folder, file.name)
``` 
<hr>
=> Fix: "Bug: After uploading an attachment I can't click on it until I refresh the page"

workflow/static/css/kanban.css, workflow/static/js/kanban.js, workflow/templates/jobs/kanban_board.html, workflow/views/kanban_view.py
Hey.
This PR focused on fixing the bug where only ten jobs were fetched to the kanban, which was preventing the users to search/view jobs that weren't loaded in the page.
Key changes:
- implement pagination and load more functionality for kanban board
- add search alert to inform users that search is limited to loaded jobs
- improve kanban board UI and UX
- add job controls for jobs per page
Tests were made (and can be checked) [here](https://workflow-app.ens.org).
=> Fix: lack of pagination in Kanban

workflow/static/js/edit_job_form_autosave.js, workflow/static/js/edit_job_grid_logic.js
Hey.
Key changes:
- changed the filename of the backup PDF to "JobSummary" to match new standard
- refactor `handleClose()` to verify existence of the JobSummary file before creating it (to decide if PUT or POST)
=> Fix: job file duplication during creation of new Backup PDF (JobSummary)

workflow/static/js/edit_job_grid_logic.js
refactor(edit_job_grid_logic.js): improve grid options handling for estimate and quote sections
This commit improves the handling of grid options for the estimate and quote sections in `edit_job_grid_logic.js`.
- Uses shallow copying to keep the renderer functions.
- Filters out empty column definitions to prevent errors.
=> Fix: trash can column not being rendered in Time Grids

workflow/static/js/job/deserialize_job_pricing.js, workflow/static/js/job/grid/grid_options.js
This PR focused on "removing" job descriptions by making their grid columns non-editable (in simple grids). Now descriptions aren't serialized anymore to simple grids and the column is empty (but still visible to the user to maintain the visual consistency and alignment to the total cost and value.
Changes to job descriptions:
* [`workflow/static/js/job/deserialize_job_pricing.js`](diffhunk://#diff-19a13567062e4cc378439521c71d16bf458a12497c4aa30be5d3f93e1fc994c8L170-R170): Set the `description` field to an empty string in the `loadSimpleJobTime`, `loadSimpleJobMaterial`, and `loadSimpleJobAdjustment` functions. [[1]](diffhunk://#diff-19a13567062e4cc378439521c71d16bf458a12497c4aa30be5d3f93e1fc994c8L170-R170) [[2]](diffhunk://#diff-19a13567062e4cc378439521c71d16bf458a12497c4aa30be5d3f93e1fc9 …
=> Remove description and refactor column alignment of simple grids

workflow/models/time_entry.py, workflow/serializers/job_pricing_serializer.py, workflow/static/js/job/edit_job_form_autosave.js, workflow/views/time_entry_view.py
This pull request includes several changes to improve the handling of job pricing and time entries in the workflow application. The most important changes include adding validation, modifying the update logic in serializers, and enhancing logging for better debugging.
* [`workflow/models/time_entry.py`](diffhunk://#diff-64f756323fbd5648feca5a0b5e0c8da2fd7bf3de4c18568ec76d023e5df63985R6): Added `ValidationError` import to enhance validation capabilities.
* [`workflow/serializers/job_pricing_serializer.py`](diffhunk://#diff-42584a312d4b4d1c2b728201b06983f7734c9d21bee00e880529d6758c49cfe1L131-R133): Modified the `update` method to prevent updating time entries when the pricing stage is `REALITY` and to remove time entries from `validated_data` in this stage. …
=> Fix: timesheets vanishing after going to related job 

workflow/static/js/job/deserialize_job_pricing.js, workflow/static/js/job/grid/grid_options.js
This pull request introduces changes to the job pricing workflow in the JavaScript files, adding a new feature to handle manual overrides for material costs and price adjustments. The most important changes include the addition of the `isManualOverride` property and the logic to manage this property when material costs or price adjustments are modified.
Enhancements to job pricing workflow:
* [`workflow/static/js/job/deserialize_job_pricing.js`](diffhunk://#diff-19a13567062e4cc378439521c71d16bf458a12497c4aa30be5d3f93e1fc994c8R271-R278): Added the `isManualOverride` property to the return objects for `SimpleMaterialsTable` and `SimpleAdjustmentsTable` to track manual overrides.
* [`workflow/static/js/job/grid/grid_options.js`](diffhunk://#diff-f60040b787d51f26a192b748ebfbb5215a6fde0cfa1d924 …
=> Feat: integrate automatic calculation of retail price for materials and adjustments in simple grids

workflow/api/xero/sync.py
This pull request includes a change to the `sync_xero_data` function in the `workflow/api/xero/sync.py` file to handle the synchronization of accounts data. The most important change is the addition of a new case for handling accounts, which includes logging the total number of accounts to be synced.
Enhancements to data synchronization:
* [`workflow/api/xero/sync.py`](diffhunk://#diff-c8d8e7f09546245380e8530c0129373db63348d1e42f7c6a25e78b1b0085c5f6R134-R143): Added a new case for "accounts" in the `sync_xero_data` function to log the total number of accounts found for synchronization.
[Copilot is generating a summary...]
=> feat(sync.py): add logging for accounts sync to track progress

workflow/api/xero/sync.py
This pull request includes a change to the `sync_xero_data` function in the `workflow/api/xero/sync.py` file to improve error handling when accessing the `pagination` attribute.
* Improved error handling when accessing `pagination` attribute in `sync_xero_data` function by using `getattr` with a default value. (`workflow/api/xero/sync.py`).
* The pagination object from the Xero API might be empty, leading to an AttributeError when trying to access item_count. This commit uses getattr with a default value to safely access item_count, preventing the error and ensuring the sync process continues smoothly.
=> fix(sync.py): safely access item_count from pagination

workflow/api/xero/reprocess_xero.py, workflow/api/xero/sync.py
This pull request includes a change to the `workflow/api/xero/reprocess_xero.py` file to handle the extraction of client fields more accurately.
* [`workflow/api/xero/reprocess_xero.py`](diffhunk://#diff-e7257933b69bfcd8458873daa9b067153ca9dc96d3b39410c1993d74f9f8ec13R157-R159): Added a check to see if the `raw_data` contains `_contacts` and if it is not empty, then set `raw_data` to the first contact in the `_contacts` list. This ensures that client fields are extracted correctly when `_contacts` is present.
=> Xero sync bug

workflow/templates/jobs/job_event_section.html, workflow/utils.py, workflow/views/edit_job_view_ajax.py
This commit fixes two issues:
1.  Updates the display of staff names in job events to use `get_display_full_name` for consistency.
2.  Improves UUID validation for `ims_payroll_id` to prevent errors when non-UUID values are present. It now attempts to convert the value to a UUID and excludes the staff ID if the conversion fails.
feat(workflow): create job object before saving
This commit modifies the job creation process to instantiate a `Job` object before saving it. This ensures that the object exists in memory before any operations are performed on it, preventing potential errors.
=> fix(workflow): resolve staff name display and UUID handling

workflow/templates/clients/add_client.html
This commit introduces a new styled alert box to display error messages when adding a new client. The alert box includes a heading, a general error message, and optional details such as the error type, the name of the client that failed to be added, and the client's email address. The alert box is initially hidden and is displayed when an error occurs. This provides a more user-friendly way to display error messages to the user.
=> feat(add_client.html): display error messages in a styled alert box

workflow/services/kpi_service.py
The date field used for grouping revenue and cost aggregations was incorrect. It was referencing `job_pricing__time_entries__date` which is not the correct field to group by date.
This commit changes the date field to `created_at__date` to ensure that the revenue and cost are correctly aggregated by date.
=> fix(kpi_service.py): correct date field for revenue and cost aggregation

apps/accounts/serializers.py
Remove extra space in deprecation message for consistency.
- …
**General**
=> style: fix double space in deprecation warning

apps/job/services/workshop_pdf_service.py
Increase main title font size for better visibility. Change main title to display "Job number" using `job.job_number`. Update job details table to show "Workshop Sheet" using `job.name`.
The changes improve the clarity and hierarchy of information on the workshop PDF. The job number is now the prominent identifier at the top of the document, making it easier to identify the specific job. The `job.name` is used to identify the "Workshop Sheet" within the details table, providing a more logical structure for job-related data.
=> feat(pdf): update workshop sheet title and job details table

apps/workflow/views/xero/xero_invoice_manager.py
Fixes invoice generation to use quoted amount for fixed price jobs instead of T&M actual cost. Fixes: https://trello.com/c/BNi30ZpO/123-quote-bug-2-invoice-on-quoted-jobs-is-wrong
=> fix: use quoted amount for fixed price jobs when creating invoices

apps/job/models/costing.py, apps/job/serializers/costing_serializer.py
Allows negative values in cost lines to support discounts, credits, and adjustments. Fixes: https://trello.com/c/jNLcplD7/116-jm-not-invoicing-properly-from-total-revenue-amount-when-adjusted
=> fix: allow negative values for adjustment cost lines

apps/accounts/__init__.py, apps/accounts/serializers.py, apps/accounts/views/staff_api.py
...and improved data handling
Introduce `GenericStaffMethodsMixin` to normalize empty string inputs for array and decimal fields in staff serializers. Create `BaseStaffSerializer` as a common base. Refactor `StaffSerializer` to use the base and explicitly define fields. Add `StaffCreateSerializer` for dedicated staff creation, handling password setting and using `StaffSerializer` for representation. Implement dynamic serializer selection in `StaffListCreateAPIView` to use the appropriate serializer for POST requests. Integrate `drf-spectacular` decorators for enhanced API documentation on staff endpoints, including examples and detailed descriptions. Add logging and error handling for staff creation.
These changes separate concerns between staff creation and update operations, improving …
=> feat(accounts): enhance staff management with dedicated create serializer

apps/job/services/kanban_categorization_service.py
=> feat: Always show Archived column on main kanban view

apps/workflow/views/xero/xero_invoice_manager.py
Removes the redundant '(Invoice)' suffix when a job description is present.
This change improves the clarity and conciseness of the generated invoice description. The `(Invoice)` suffix is now only appended when the job description is empty, preventing duplication and unnecessary verbosity in the final description string. The context of the document being an invoice is already clear, making the suffix redundant when a job description is provided.
Fixes [this.](https://trello.com/c/moNa6MwM/151-recently-we-have-seen-invoice-added-to-the-description-on-the-invoices-above)
=> refactor(xero): streamline invoice description generation
