workflow/static/js/client_lookup.js, workflow/static/js/edit_job_form_autosave.js, workflow/static/js/edit_job_grid_logic.js, workflow/templates/jobs/edit_job_detail_section.html
Enhancements to **Job Management** Interface
This commit introduces several key enhancements and fixes to improve the functionality and user experience of the job management system:
Dropdown Fix in client_lookup.js: Resolved issues with the dropdown behavior which were affecting user interaction. This fix ensures that the dropdown now operates smoothly and correctly displays the available options based on the user's input.
Copy Estimates to Quotes in edit_job_form_autosave.js: Implemented the copyEstimateToQuote function to allow users to effortlessly transfer estimates to the quotes section with a single click. This update enhances the workflow by minimizing the need for redundant data entry and reducing potential errors.
Integration of copyEstimateToQuote in edit_job_grid_logic.js: …
=> Jobs Section Fixes

file_interaction.mermaid, workflow/api/server.py, workflow/api/xero/reprocess_xero.py, workflow/api/xero/sync.py, workflow/api/xero/xero.py, workflow/static/js/client_table_populate.js, workflow/static/js/filter_clients.js, workflow/templates/base.html, workflow/templates/clients/list_clients.html, workflow/templates/xero/xero_index.html, workflow/urls.py, workflow/views/client_view.py, workflow/views/report_view.py, workflow/views/xero_view.py
Getting close.  Just need to tidy the serializer so it sends to Xero correctly.
=> Client editor

file_interaction.mermaid, workflow/api/xero/sync.py, workflow/models/client.py
Ability to create and edit clients
=> client_deitor

workflow/management/commands/create_shop_jobs.py, workflow/models/job.py, workflow/models/staff.py
Added Staff password setter to Staff model
Added "shop_job" property setter so `create_shop_jobs` works
=> Little problem fixing for production configuration

workflow/admin.py, workflow/models/staff.py, workflow/urls.py
fix(workflow): remove password property from staff model
fix(workflow): remove unused import
=> feat(workflow): remove charge_out_rate from staff model and admin

workflow/static/js/deseralise_job_pricing.js, workflow/static/js/edit_job_form_autosave.js, workflow/static/js/edit_job_grid_logic.js, workflow/urls.py, workflow/views/edit_job_view_ajax.py
✨ Enhancements & Fixes:
🚀 Improved Required Field Validation (edit_job_form_autosave.js)(Trello: [k2x6znFP](https://trello.com/c/k2x6znFP/2-autosave-reports-it-is-successful-even-if-it-fails))
k2x6znFP
- Added red border (is-invalid) for empty required fields.
- Auto-scrolls and focuses on the first missing field when saving.
- Removes validation error dynamically when the user starts typing.
- 
⚡ Fixed Immediate Retail Rate Calculation (edit_job_grid_logic.js) (Trello: [RhOpbg2D](https://trello.com/c/RhOpbg2D/1-markup-not-working))
- Auto-calculates Retail Rate when Cost Rate is changed, even before focus moves.
- Detects Tab & Enter keypresses to ensure instant updates.
- Prevents recalculations from overriding manually entered values.
⏳ Entering Time in the Estimates (Trello: …
=> Enhance Job Form Validation, Auto-Calculation & UI Fixes for Estimates & Revenue Table

adhoc/deploy_app.sh, adhoc/deploy_release.sh, adhoc/xero-sync.service, jobs_manager/settings/production_like.py
=> Require xero client

workflow/static/js/job/deserialize_job_pricing.js, workflow/static/js/job/edit_job_form_autosave.js, workflow/static/js/job/grid/grid_options.js
This pull request includes some enhancements related to validation error handling, to provide a more user-friendly error report in case of errors during autosave, specifically with errors returned by the serializer.
Improvements to error handling:
* [`workflow/static/js/job/edit_job_form_autosave.js`](diffhunk://#diff-e85d2725b4ef72d6d82e485e2a358b233bdacb1bb8186ee6c6799aff1db8a130R1136-L1146): Enhanced the `saveDataToServer` function to extract and display detailed error messages using a new helper function `extractErrorMessages`. [[1]](diffhunk://#diff-e85d2725b4ef72d6d82e485e2a358b233bdacb1bb8186ee6c6799aff1db8a130R1136-L1146) [[2]](diffhunk://#diff-e85d2725b4ef72d6d82e485e2a358b233bdacb1bb8186ee6c6799aff1db8a130R1174-R1203)
* …
=> Feat: enhance validation error handling

workflow/static/js/job/deserialize_job_pricing.js, workflow/static/js/job/edit_job_form_autosave.js, workflow/static/js/job/grid/grid_options.js, workflow/static/js/job/job_file_handling.js, workflow/templates/jobs/edit_job_ajax.html, workflow/views/edit_job_view_ajax.py
This pull request includes several changes to improve error handling, file upload processes, and grid behavior in the job workflow system. The most important changes include adding error message extraction, refactoring the file upload process, and enhancing grid behavior for pricing tables.
* [`workflow/static/js/job/job_file_handling.js`](diffhunk://#diff-93680e5541bbd59712a9b90b9f4f99448f0a7f5964ea283dd3d680c92cc67987L16-R109): Refactored file upload process into multiple functions (`createFileFormData`, `sendFileRequest`, `processUploadResponse`, etc.) to improve readability and maintainability.
* [`workflow/static/js/job/job_file_handling.js`](diffhunk://#diff-93680e5541bbd59712a9b90b9f4f99448f0a7f5964ea283dd3d680c92cc67987L249-R441): Added visual feedback for file upload progress and …
=> Feat: Job file upload feedback

workflow/static/css/timesheet-enhanced.css, workflow/static/js/timesheet/export_to_ims.js, workflow/views/time_overview_view.py
This pull request includes significant updates to the timesheet export and overview functionalities, focusing on enhancing the user interface and improving the code structure. The most important changes include adding new styles for the IMS export table, updating the JavaScript logic for better handling of timesheet data, and improving the initialization and submission of the Paid Absence Modal.
* [`workflow/static/css/timesheet-enhanced.css`](diffhunk://#diff-f59e60a10330505b5af1998a65ec7a3d8cf7bb06ca9598063e2098dd9f27ec89R557-R824): Added comprehensive styling for the IMS export table, including container, data cells, hour rows, status indicators, and leave sections.
* [`workflow/static/js/timesheet/export_to_ims.js`](diffhunk://#diff-cb148e08c07197d8d2b8c75c4e1da270396d42e7b1a9f8e2702da …
=> IMS Entry Enhancements

workflow/services/job_service.py, workflow/static/css/historical_pricing.css, workflow/static/js/job/edit_job_form_autosave.js, workflow/static/js/job/historical_pricing_navigation.js, workflow/static/js/job/index.js, workflow/static/js/job/job_buttons/button_utils.js, workflow/templates/jobs/edit_job_ajax.html, workflow/views/edit_job_view_ajax.py
**Summary**
This PR introduces a new Historical Pricing Navigation feature that allows users to browse through snapshots of job pricing data over time.
**Feature Details**
- _Timeline Navigation:_ Simple UI controls (Previous/Next buttons) to move through chronological snapshots of pricing data
- _Date Indicators:_ Clear visual indication of which historical snapshot is being viewed 
- _Non-destructive Viewing:_ View historical data without modifying current job information  
- _Return to Current:_ One-click option to return to current pricing data Technical Implementation
**Technical Implementation**
- Created a new module historical_pricing_navigation.js to handle navigation logic 
- Implemented a bi-directional data flow system between historical API data and grid displays
- Added …
=> Historical Pricing Navigation

workflow/api/xero/sync.py
This commit adds a new case to the sync_xero_data function to handle the "accounts" entity type. This allows the function to correctly process and display the progress of syncing accounts data from Xero.
=> feat(xero/sync.py): add accounts case to sync_xero_data function

workflow/api/xero/sync.py
This change introduces a new function `get_or_fetch_client_by_contact_id` that retrieves a client by its Xero contact ID. If the client is not found locally, it fetches it from the Xero API and syncs it to the database. This ensures that invoices can be processed even if the client is not initially present in the local database.
The `sync_invoices` function is updated to use the new `get_or_fetch_client_by_contact_id` function to retrieve the client for an invoice. This eliminates the need to raise an error if the client is not found locally, as it will now be fetched from the API.
=> feat(xero/sync.py): fetch client by contact ID if not found locally

workflow/api/xero/sync.py, workflow/management/commands/start_xero_sync.py
This commit improves the reliability and error handling of the Xero synchronization process. It introduces a new function `get_or_fetch_client_by_contact_id` to handle client retrieval, creation, and error scenarios consistently across different sync functions (bills, credit notes, quotes, purchase orders).
The previous implementation used `Client.objects.filter(...).first()`, which could lead to issues if the client was not found. The new approach encapsulates the logic for fetching or creating the client and raises a ValueError if an error occurs during this process. This allows for better error reporting and handling in the calling functions.
The sync functions (sync_bills, sync_credit_notes, sync_quotes, sync_purchase_orders) are updated to use the new …
=> feat(xero): refactor client retrieval and error handling during sync

workflow/static/js/job/edit_job_grid_logic.js, workflow/static/js/job/grid/grid_utils.js, workflow/static/js/job/job_buttons/button_handlers.js, workflow/static/js/job/job_buttons/button_utils.js, workflow/static/js/job/job_file_handling.js
This pull request includes several changes to the job grid logic in the `workflow/static/js/job` directory. The primary focus is on adding functionality to check job acceptance and lock grids accordingly, as well as updating job status. Below are the most important changes:
* Added `checkJobAccepted` to `grid_utils.js` to check the job status and lock grids if the job is accepted.
* Added `lockQuoteGrids` and `updateJobStatus` to `button_utils.js` to handle locking grids and updating job status respectively.
* Updated `edit_job_grid_logic.js` to import `checkJobAccepted` and add event listeners for job status changes. [[1]](diffhunk://#diff-e8f943218db3da25fd6cd95f0b54650272cf3d3de34ee17256d5e044844b5cffL63-R63) [[2]](diffhunk://#diff-e8f943218db3da25fd6cd95f0b54650272cf3d3de34ee17256d5e04 …
=> feat(workflow): lock quote grids and update job status on quote acceptance

workflow/static/css/edit_job.css, workflow/static/css/enhanced-grid.css, workflow/static/js/job/advanced_search.js, workflow/static/js/job/deserialize_job_pricing.js, workflow/static/js/job/edit_job_grid_logic.js, workflow/static/js/job/grid/grid_options.js, workflow/static/js/job/grid/grid_utils.js, workflow/static/js/xero_sync.js, workflow/templates/clients/add_client.html, workflow/templates/jobs/edit_job_workflow_section.html, workflow/views/kanban_view.py
This pull request includes a variety of changes to the CSS and JavaScript files in the `workflow` directory, focusing on improving grid functionality, enhancing user experience, and fixing minor bugs. The most important changes are categorized below:
* [`workflow/static/css/enhanced-grid.css`](diffhunk://#diff-f214e3cf93473311572290c165509004cde541baef8a9112c76a96552e57b107L23-R36): Introduced conditional overflow handling based on the number of rows, ensuring that grids with fewer rows have overflow hidden while those with many rows have overflow visible. [[1]](diffhunk://#diff-f214e3cf93473311572290c165509004cde541baef8a9112c76a96552e57b107L23-R36) [[2]](diffhunk://#diff-f214e3cf93473311572290c165509004cde541baef8a9112c76a96552e57b107L42-R53) …
=> Milestone plan

workflow/static/js/job/job_buttons/xero_handlers.js, workflow/views/xero/xero_quote_creator.py
This pull request introduces improvements to the handling of Xero documents in both the frontend and backend code. Key changes include refining user-facing messages, enhancing the logic for document deletion, and ensuring required fields are included in API calls.
* **Dynamic Button Text Updates**: Updated the button text in `createXeroDocument` to dynamically reflect the document type (`Invoicing` or `Quoting`) for better user clarity. (`workflow/static/js/job/job_buttons/xero_handlers.js`, [workflow/static/js/job/job_buttons/xero_handlers.jsL15-R16](diffhunk://#diff-40476c562679ac6887a45490d7c604cd7c7e40aa5c769ad68d3c5120a074ca8cL15-R16))
* **Improved Deletion Messages**: Modified the success message in `deleteXeroDocument` to use the `capitalize` utility function, ensuring the document …
=> feat(xero_handlers.js): improve UX when creating Xero documents

.gitignore, workflow/services/kpi_service.py, workflow/static/js/kpi_calendar.js, workflow/static/js/timesheet/timesheet_entry/messages.js, workflow/templates/reports/kpi_calendar.html
This pull request enhances the KPI calendar feature by introducing detailed revenue, cost, and profit breakdowns for individual days, improving the user interface, and refining the JavaScript logic for better maintainability and functionality. Key changes include adding a modal for day-specific details, updating the backend to provide detailed data, and improving the styling and interactivity of the calendar.
* Added a `details` dictionary in the `get_calendar_data` method to include revenue, cost, and profit breakdowns for each day. This enables more granular data visualization in the frontend. (`workflow/services/kpi_service.py`, [workflow/services/kpi_service.pyL268-R283](diffhunk://#diff-43e50406eeba7c3c9879df45d9f21bb0d93a168a395c987e1f202fc6a88d39f7L268-R283))
* Introduced the …
=> KPI Reports enhancement: add KPI card to calendar

.github/workflows/claude-code-review.yml, .github/workflows/claude.yml
=> Add claude GitHub actions 1751315770931

apps/accounting/services.py, apps/accounting/urls.py, apps/accounting/views/__init__.py, apps/job/migrations/0030_migrate_pricing_to_costing_and_cleanup.py, apps/workflow/api/xero/sync.py
=> Job aging report, and fixes to migration to costings

apps/accounting/models/quote.py, mypy.ini, python_files_to_process.txt
=> Hopefully commit to the branch thsi time

docs/server_setup.md, jobs_manager/settings.py
=> Dropbox - removed default

apps/job/apps.py, apps/quoting/apps.py, apps/workflow/apps.py, docs/server_setup.md, jobs_manager/settings.py
=> CLeaner handling of start scheduler

scripts/deploy_machine.sh, scripts/startup-deploy.cron
=> Tweak to deploy script

scripts/deploy.sh
=> Remove all prerequisite validation checks

scripts/auto_shutdown.sh
=> Xero serialiser fix

.github/workflows/cd.yml
Debug deployment issues and improve UAT dual-machine deployment process
=> UAT deployment improvements with debugging

scripts/deploy_machine.sh
- Remove BRANCH_NAME variable and hardcode 'main' throughout
- Use git reset --hard to handle permission conflicts
- Add chmod +x after sync to ensure script stays executable
- Simplifies script since CD workflow only runs on main branch
- …
**General**
=> simplify: hardcode main branch since CD only triggers on main

apps/job/models/costing.py
The `_update_cost_set_summary` method now merges new cost, revenue, and hours into the `cost_set.summary` field. Previously, this method would overwrite the entire summary dictionary, leading to the loss of other summary fields, such as revision history. This change ensures that all existing summary data is retained when updating aggregated cost, revenue, and hours.
The `_update_cost_set_summary` method was overwriting the entire `cost_set.summary` dictionary, which could lead to the loss of other important data stored within that dictionary, such as revision history. The change ensures that new aggregated data (cost, revenue, hours) is merged into the existing summary, preserving any other fields.
=> fix(costing): preserve existing summary data when updating cost set

apps/workflow/management/commands/run_scheduler.py, jobs_manager/settings.py, scripts/deploy_machine.sh
=> 100 deployments migrations are broken in production

scripts/json_to_mysql.py
=> Test commit with SSH signing

.gitignore, docs/backup-restore-process.md, package-lock.json, package.json, scripts/validate_restore_progress.py
=> ignore adhoc in git always

apps/purchasing/views/purchasing_rest_views.py
=> FOrmatting

package-lock.json, package.json, scripts/analyze_captures.js, scripts/capture_metrics.js
=> Added puppeteer analysis scripts

apps/job/services/kanban_service.py
=> Include fully invoiced in kanban

apps/job/serializers/__init__.py, apps/job/serializers/data_quality_report_serializers.py, apps/job/services/__init__.py, apps/job/services/data_quality_report.py, apps/job/services/kanban_service.py, apps/job/urls_rest.py, apps/job/views/__init__.py, apps/job/views/archive_completed_jobs_view.py, apps/job/views/data_quality_report_views.py, docs/urls/job.md
=> Dq report support

apps/job/serializers/job_serializer.py, apps/job/views/job_rest_views.py
=> Support for rjected setting

apps/job/serializers/job_serializer.py, apps/job/services/job_rest_service.py, docs/plans/BACKEND_CHANGES_COSTLINE_ESTIMATE.md
=> Moved CostLines from frontend to backend.

apps/workflow/api/xero/sync.py
=> Fail early in syncs

apps/accounting/signals.py, apps/workflow/api/xero/sync.py
=> Shifting towards deleting the signals.
